UI.Mvc/Controllers/CommentController.cs
using BLL.Interface.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using UI.Mvc.Infrastructure.Mappers;

namespace UI.Mvc.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService commentService;
        private readonly IUserService userService;
        public CommentController(ICommentService ics, IUserService ius)
        {
            commentService = ics;
            userService = ius;
        }

        [Authorize]
        public async Task<ActionResult> Add(string text, int? lotid)
        {
            if (string.IsNullOrEmpty(text))
                return null;

            if (Request.IsAjaxRequest())
            {
                int comentId = await commentService.PostComment(text, User.Identity.Name, lotid.Value);
                var commentView = (await commentService.GetById(comentId)).ToMvcComment(userService);

                return PartialView("Partial/Comment", commentView);
            }

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public async Task<ActionResult> Delete(int? id, int? auctionId)
        {
            if (id == null || auctionId == null || id.Value < 1 || auctionId.Value < 1)
                return RedirectToAction("Index", "Home");

            await commentService.Delete(id.Value);
            return RedirectToAction("Details", "Auction", new { id = auctionId });
        }

        public async Task<ActionResult> GetComments(int? page, int? lotid)
        {
            int pageSize = 10;
            if (Request.IsAjaxRequest())
            {
                page = page ?? 1;
                var results = (await commentService.GetRange((page.Value - 1) * pageSize, pageSize, t => t.Lot == lotid)).Select(t => t.ToMvcComment(userService));
                return PartialView("Partial/CommentsPartial", results);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

UI.Mvc/Controllers/SearchController.cs
using BLL.Interface.Services;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using UI.Mvc.Infrastructure.Mappers;
using UI.Mvc.Models;

namespace UI.Mvc.Controllers
{
    public class SearchController : Controller
    {
        private readonly IAuctionService<int> auctionService;

        public SearchController(IAuctionService<int> iau)
        {
            auctionService = iau;
            Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
        }
        public async Task<ActionResult> Find(string query, int? page, int? catId)
        {
            int pageSize = 15;
            page = page ?? 1;
            SearchResult<LotModel> searchResult;
            if (string.IsNullOrEmpty(query))
            {
                IEnumerable<LotModel> emptyQueryResults;
                if (catId.HasValue)
                {
                    int cat = catId.Value;
                    ViewData["CatId"] = catId;
                    emptyQueryResults = (await auctionService.GetRange(0, pageSize, t => t.Categorie == cat)).Select(t => t.ToLotMvc());
                }
                else
                {
                    emptyQueryResults = (await auctionService.GetRange(0, pageSize)).Select(t => t.ToLotMvc());
                }
                if (emptyQueryResults.Count() != 0)
                {
                    searchResult = new SearchResult<LotModel>(emptyQueryResults, auctionService.Count(), 1);
                    return View(searchResult);
                }
                else
                {
                    ViewData["NoResults"] = "No results for your query.";
                    return View();
                }
            }

            DateTime now = DateTime.Now;
            var results = (await auctionService.GetRange((page.Value - 1) * pageSize, pageSize, t => t.Title.Contains(query) || t.Description.Contains(query) && t.AuctionEndDate >= now)).Select(t => t.ToLotMvc());
            if (results.Count() <= 0)
            {
                ViewData["NoResults"] = "No results for your query.";
                return View();
            }
            searchResult = new SearchResult<LotModel>(results, auctionService.Count(t => t.Title.Contains(query) || t.Description.Contains(query)), page.Value);
            return View(searchResult);
        }
    }
}

UI.Mvc/Views/Shared/Partial/CategoriesListPartial.cshtml
@{ 
    IEnumerable<UI.Mvc.Models.Category> Categories = (IEnumerable<UI.Mvc.Models.Category>)ViewData["Categories"];
}

<div class="row">
    <div class="col-md-12">
        <h3>Categories</h3>
        <hr />
        <div class="categorie-list">
            @foreach (var cat in Categories)
            {
                @Html.ActionLink(cat.Name, "Find", "Search", new { catId = cat.Id }, new { @class = "categorie-list-item" })
            }
        </div><!-- /categorie-list-->
    </div><!-- /col-md-12-->
</div><!-- /row-->

UI.Mvc/Views/Shared/Partial/Comment.cshtml
@model UI.Mvc.Models.Comment

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">@Model.UserName <small>(@Model.PubDate.ToLongDateString())</small></h3>
    </div>
    <div class="panel-body">
        <p>
            @Model.Text
        </p>
    </div>
</div>

UI.Mvc/Views/Shared/Partial/CommentsInputPartial.cshtml
@model UI.Mvc.Models.AuctionDetail

@if (User.Identity.IsAuthenticated)
            {
    <div class="cssload-container" id="ajax-loader">
        <div class="cssload-whirlpool"></div>
    </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Post your comment</h3>
                    </div>
                    <div class="panel-body">
                        @using (Ajax.BeginForm("Add", "Comment", new AjaxOptions() { UpdateTargetId = "comments", InsertionMode = InsertionMode.InsertBefore, LoadingElementId = "ajax-loader" }))
                        {
                            @Html.TextArea("text", new { @class = "form-control full-width" });
                            @Html.Hidden("lotid", Model.Id);
                            <br />
                            <button type="submit" class="btn btn-primary">Post</button>
                        }
                    </div>
                </div>
}
else
{
    <div>
        <span class="alert alert-warning"><b>Sign in to leave comments.</b></span>
        <br /><br />
    </div>
}

UI.Mvc/Views/Shared/Partial/CommentsPartial.cshtml
@model IEnumerable<UI.Mvc.Models.Comment>

@foreach (var item in Model)
{
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">@item.UserName <small>(@item.PubDate.ToLongDateString())</small></h3>
            @if (User.IsInRole("admin"))
            {
                @Html.ActionLink("Delete", "Delete", "Comment" , new { id = item.Id, auctionId = item.LotId }, null);
            }
        </div>
        <div class="panel-body">
            <p>
                @item.Text
            </p>
        </div>
    </div>
}

UI.Mvc/Views/Shared/Partial/LoginNavbarPartial.cshtml
@if (User.Identity.IsAuthenticated)
{
    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Welcome back, @User.Identity.Name<span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="@Url.Action("Create", "Auction")"><span class="glyphicon glyphicon-plus"></span> Sold item</a></li>
                <li><a href="@Url.Action("My", "Auction")"><span class="glyphicon glyphicon-list"></span> My auctions</a></li>
                <li><a href="@Url.Action("MyBids", "Auction")"><span class="glyphicon glyphicon-hand-up"></span> My bids</a></li>
                <li role="separator" class="divider"></li>
                <li>@Html.ActionLink("Log out", "Logout", "Account", null, null)</li>
            </ul>
        </li>
    </ul>
}
else
{
    using (Html.BeginForm("Login", "Account", FormMethod.Post, new { @class = "navbar-form navbar-right form-login" }))
    {
        @Html.TextBox("login", null, new { placeholder = "Login", @class = "form-control" })
        @Html.Password("password", null, new { placeholder = "Password", @class = "form-control" })
        <button class="btn btn-default" type="submit">Sign In</button>
        @Html.ActionLink("Register", "Register", "Account", null, new { @class = "btn btn-link" })
    }
}

UI.Mvc/Views/Shared/Partial/LotListPartial.cshtml
@model IEnumerable<UI.Mvc.Models.LotModel>


@foreach (var lot in Model)
{
    <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
            @if (lot.Photos != Enumerable.Empty<string>())
            {
                <img src="@lot.Photos.FirstOrDefault()" alt="@lot.Title">
            }
            else
            {
                <img src="~/Content/no_photo.jpg" alt="@lot.Title">
            }
            <div class="caption">
                <h4>@lot.Title</h4>
                <p>
                    <span class="label label-primary">@lot.CreationDate</span>
                    <span class="label label-success">@lot.EndDate</span>
                </p>
                <p>Current price: <span class="">$@lot.CurrentPrice</span></p>
                <p>@Html.ActionLink("Details", "Details", "Auction", new { id = lot.Id }, new { @class = "btn btn-info" })</p>
            </div>
        </div>
    </div>
}

UI.Mvc/Views/Shared/Partial/MyAuctionsPartial.cshtml
@model IEnumerable<UI.Mvc.Models.LotModel>

@foreach (var item in Model)
{
    <tr>
        <td>@Html.ActionLink(item.Title, "Details", new { id = item.Id })</td>
        <td>@item.CreationDate.ToLongDateString()</td>
        <td>@item.EndDate.ToLongDateString()</td>
    </tr>
}

UI.Mvc/Views/Shared/Partial/MyBidsPartial.cshtml
@model IEnumerable<UI.Mvc.Models.Bid>

@foreach (var item in Model)
{
    <tr>
        <td>@Html.ActionLink($"#{item.LotId.ToString()}", "Details", new { id = item.LotId })</td>
        <td>@item.MoneyAmount.ToString()</td>
        <td>@item.BidDate.ToLongDateString()</td>
    </tr>
}

UI.Mvc/Views/Shared/Partial/SearchResultPartial.cshtml
@model UI.Mvc.Models.LotModel

@{ 
    string Title = Model.Title;
    string Description = Model.Description;
}

<div class="row">
    <div class="col-md-2">
        <a href="/Auction/Details/@Model.Id" class="thumbnail">
            @if (Model.Photos != Enumerable.Empty<string>())
            {
                <img src="@Model.Photos.FirstOrDefault()" alt="@Model.Title" />
            }
            else
            {
                <img src="~/Content/no_photo.jpg" alt="@Model.Title">
            }
        </a>
    </div>
    <div class="col-md-2">
            @if (Model.Title.Length > 100)
            {
                Title = Model.Title.Remove(100);
            }
             <a href="/Auction/Details/@Model.Id"><h4>@Title</h4></a>
    </div>
    <div class="col-md-4">
        <p>
            @if (Model.Description.Length > 255)
            {
                Description = Model.Description.Remove(255);
            }
             @Description
        </p>
    </div>
    <div class="col-md-2">
        <span>@Model.CreationDate.ToLongDateString()</span>
    </div>
    <div class="col-md-2">
        <span>@Model.EndDate.ToLongDateString()</span>
    </div>
</div>